### ISSUE TITLE
Evitar que se abra la ventana de diálogo para ejecutar el geometry preprocessor

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#10]
Al iniciarse una simulación, el HEC-RAS busca los archivos .x y .c,  y si no existen corre el geometry processor para generarlos. El problema es que abre una ventana de diálogo en la máquina virtual para que el usuario acepte esto. Para evitar que se requiera esta interacción del usuario, antes de generar una nueva simulación, hice lo siguiente:
- Abrir HEC-RAS en la máquina virtual
- Abrir el projecto
- Ir a Run -> Unsteady Flow Analysis
- Seleccionar la casilla Programs to run -> Geometry Preprocessor
- Cerrar la ventana de Unsteady Flow Analysis SIN EJECUTAR
- Ir a File -> Save Project
- Cerrar HEC-RAS

Con esto se tienen que haber modificado los archivos .prj y .p. Usar éstos para generar una nueva simulación. Luego, al ejecutar la simulación, debería correr el geomerty processor automáticamente (y así no bloquear la ejecución de la simulación).

**Comment by manulon** [comment]
Era un problema de configuracion de HEC-RAS, ya está resuelto.
