### ISSUE TITLE
Error al intentar eliminar execution_plan cuando hay execution_tasks asociadas

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#14]
curl -X DELETE "http://localhost:5001/api/execution_plan/1" -H  "accept: */*"
{
  "error": "(psycopg2.errors.ForeignKeyViolation) update or delete on table \"execution_plan\" violates foreign key constraint \"execution_plan__id_fk\" on table \"execution_tasks\"\nDETAIL:  Key (id)=(1) is still referenced from table \"execution_tasks\".\n\n[SQL: DELETE FROM gesina.execution_plan WHERE gesina.execution_plan.id = %(id)s]\n[parameters: {'id': 1}]\n(Background on this error at: https://sqlalche.me/e/14/gkpj)",
  "message": "error deleting execution plan 1"
}

**Comment by federicoburman** [comment]
Arreglado
