### ISSUE TITLE
GET api/schedule_task/all error Id is not numeric

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#15]
curl -X GET "http://localhost:5001/api/schedule_task/all?date_from=2021-01-01T00%3A00%3A00&date_to=2024-04-01T00%3A00%3A00" -H  "accept: application/json"

Response
code: 400
Message:
{
  "error": "Id is not numeric",
  "message": "bad request while getting scheduled task all"
}

**Comment by cerobpm** [comment]
@federicoburman @azulzaietz @manulon

**Comment by federicoburman** [comment]
Lo miramos. Es un tema de formato de fechas

**Comment by federicoburman** [comment]
No era formato de fecha, estaba desactualizado el swagger

**Comment by azulzaietz** [comment]
Ya está el fix en main!

**Comment by federicoburman** [comment]
@cerobpm Se puede cerrar el issue
