### ISSUE TITLE
api/schedule_task/copy devolver id de nueva schedule_task

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#16]
Actualmente la respuesta es
{"message":"Scheduled task with id 1 copied successfully"}
Pero estaría bueno que devuelva también el id de la copia, por ejemplo
{"message":"Scheduled task with id 1 copied successfully", "id": 2}

@azulzaietz @manulon @federicoburman

**Comment by federicoburman** [comment]
Ya en la rama dev. Se puede cerrar el issue @cerobpm
