### ISSUE TITLE
scheduled task eliminada sigue generando tareas

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#18]
Al eliminar una corrida programada que estaba habilitada (enabled=true), sigue generando tareas, las cuales, al no encontrar el registro en base de datos, fallan con este mensaje en el log del scheduler:

gesina-scheduler-1  | ERROR:apscheduler.executors.default:Job "ScheduledTaskJob.simulate (trigger: interval[0:05:00], next run at: 2024-03-08 19:24:41 UTC)" raised an exception
gesina-scheduler-1  | Traceback (most recent call last):
gesina-scheduler-1  |   File "/usr/local/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
gesina-scheduler-1  |     retval = job.func(*job.args, **job.kwargs)
gesina-scheduler-1  |   File "/src/src/scheduler.py", line 53, in simulate
gesina-scheduler-1  |     start_date = today - timedelta(scheduled_task.observation_days)
gesina-scheduler-1  | AttributeError: 'NoneType' object has no attribute 'observation_days'

@azulzaietz @manulon @federicoburman

**Comment by manulon** [comment]
Hola! este problema no es puramente de este issue pero tiene relacion con las scheduled task.
Al armar un scheduled task se usan las series del INA, basandose en valores que obtienen de la pagina oficial. El endpoint tiene la siguiente pinta: 'https://alerta.ina.gob.ar/a6/sim/calibrados/1/corridas/last?series_id=31556&timestart=2024-03-07&timeend=2024-03-11'.

Al querer accederlo nos salta error '401 Unauthorized' y vimos que para poder usar dicho endpoint necesitamos un token, ¿donde podemos obtenerlo? ¿se pide en algun lado o nos lo proporcionan ustedes?

![image](https://github.com/jbianchi81/gesina/assets/45469722/ea2170d0-8a64-48b7-8702-b88469245129)
![image](https://github.com/jbianchi81/gesina/assets/45469722/af745e6b-ba7c-4200-a2f6-7802f4a9851a)

**Comment by jbianchi81** [comment]
Hola,
Les mandé credenciales por mail.

**Comment by federicoburman** [comment]
Bug Arreglado y mergeado a dev

**Comment by federicoburman** [comment]
@jbianchi81
