### ISSUE TITLE
Falta stage_datum en plan_series_list de la respuesta a GET /schedule_task

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#19]
Este commit lo arregla: https://github.com/jbianchi81/gesina/commit/dd33e91ff7718477c74e4c94e3195eba2885e651

**Comment by cerobpm** [comment]
@federicoburman
@manulon
@azulzaietz

**Comment by federicoburman** [comment]
Lo agregamos, gracias!

**Comment by federicoburman** [comment]
se puede cerrar @jbianchi81 @cerobpm
