### ISSUE TITLE
Bug en el chequeo de header del csv de plan_series - adaptar para que incluya la columna stage_datum

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#20]
Este commit lo arregla: https://github.com/jbianchi81/gesina/commit/562c624576dfa408beab19718e381d7d3fd72aea

**Comment by cerobpm** [comment]
@federicoburman
@manulon
@azulzaietz

**Comment by federicoburman** [comment]
Ya esta arreglado aca https://github.com/manulon/gesina-core-api-2.0/pull/69/files

**Comment by federicoburman** [comment]
@jbianchi81 @cerobpm se puede cerrar
