### ISSUE TITLE
En la respuesta a GET scheduled_task, a los items de plan_series les falta el stage_datum ("stage_datum" : null)

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#22]
En la respuesta a GET scheduled_task, a las plan_series les falta el stage_datum (da nulls)

**Comment by federicoburman** [comment]
fixeado aca https://github.com/manulon/gesina-core-api-2.0/pull/74
Cuando se creaba un plan_series no se agregaba el stage_datum a la bdd
