### ISSUE TITLE
POST api/execution_plan error: "'NoneType' object has no attribute 'split'"

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#25]
POST api/execution_plan

Request body:
    
    {
      "created_at": "2024-04-26 16:17:07.549837",
      "end_datetime": "2024-04-26 13:17:37.072935",
      "execution_files": [
        {
          "name": "DeltaParana_2016.g23"
        },
        {
          "name": "restart_file.rst"
        },
        {
          "name": "scheduled-task.p01"
        },
        {
          "name": "scheduled-task.prj"
        },
        {
          "name": "scheduled_task.u01"
        }
      ],
      "execution_output_list": [
        {
          "reach": " 2b",
          "river": "Parana",
          "river_stat": "223194.8",
          "stage_datum": 3.625
        },
        {
          "reach": " Desembocadura",
          "river": "SanAntonio",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "CanaldelEste",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "Mini",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "LaBarquita",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "BarcaGrande",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "Sauce",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "Bravo",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "Gutierrez",
          "river_stat": "1960.748",
          "stage_datum": 0
        },
        {
          "reach": "1",
          "river": "CarabelasGrande",
          "river_stat": "33.3",
          "stage_datum": 0
        },
        {
          "reach": " Victoria",
          "river": "Victoria",
          "river_stat": "82.92",
          "stage_datum": 1.536
        },
        {
          "reach": " RioBaradero",
          "river": "RioBaradero",
          "river_stat": " 29.092*",
          "stage_datum": 0.641
        },
        {
          "reach": "4",
          "river": "Parana",
          "river_stat": "498.7283",
          "stage_datum": 1.37
        },
        {
          "reach": "3",
          "river": "Parana",
          "river_stat": "44071.76",
          "stage_datum": 0.714
        },
        {
          "reach": "3",
          "river": "Parana",
          "river_stat": "94846.95",
          "stage_datum": 1.642
        },
        {
          "reach": "3",
          "river": "Parana",
          "river_stat": "126030.6",
          "stage_datum": 1.954
        },
        {
          "reach": " 2b",
          "river": "Parana",
          "river_stat": "143588.9",
          "stage_datum": 1.981
        },
        {
          "reach": " 2b",
          "river": "Parana",
          "river_stat": "188533.7",
          "stage_datum": 3.032
        },
        {
          "reach": " Desembocadura",
          "river": "Lujan",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " 2b",
          "river": "Parana",
          "river_stat": "237194.8",
          "stage_datum": 0
        },
        {
          "reach": " ParanaAA",
          "river": "Parana",
          "river_stat": "18.96",
          "stage_datum": 6.763
        },
        {
          "reach": " ParanaAA",
          "river": "Parana",
          "river_stat": "224000",
          "stage_datum": 9.432
        },
        {
          "reach": " Desembocadura",
          "river": "Palmas",
          "river_stat": "6246.783",
          "stage_datum": -0.337
        },
        {
          "reach": "8",
          "river": "Palmas",
          "river_stat": "21307.62",
          "stage_datum": 0
        },
        {
          "reach": "5",
          "river": "Palmas",
          "river_stat": "45033.09",
          "stage_datum": -0.656
        },
        {
          "reach": "4",
          "river": "Palmas",
          "river_stat": "49019.05",
          "stage_datum": 0.03
        },
        {
          "reach": "4",
          "river": "Palmas",
          "river_stat": "57113.41",
          "stage_datum": 0.418
        },
        {
          "reach": "3",
          "river": "Palmas",
          "river_stat": "68418.45",
          "stage_datum": 0.243
        },
        {
          "reach": "3",
          "river": "Palmas",
          "river_stat": "94654.47",
          "stage_datum": -0.556
        },
        {
          "reach": "2",
          "river": "Palmas",
          "river_stat": "101864.4",
          "stage_datum": 1.156
        },
        {
          "reach": " Desembocadura",
          "river": "Mini",
          "river_stat": "11.9",
          "stage_datum": -0.286
        },
        {
          "reach": "2",
          "river": "Lujan",
          "river_stat": "5.828",
          "stage_datum": -0.099
        },
        {
          "reach": "1",
          "river": "Lujan",
          "river_stat": "18.0191",
          "stage_datum": -0.074
        },
        {
          "reach": "1",
          "river": "Lujan",
          "river_stat": "24.421",
          "stage_datum": 0
        },
        {
          "reach": " Ibicuy",
          "river": "Ibicuy",
          "river_stat": "7.16",
          "stage_datum": 0.456
        },
        {
          "reach": " Desembocadura",
          "river": "Gutierrez",
          "river_stat": "19967.07",
          "stage_datum": 0.39
        },
        {
          "reach": "3",
          "river": "Guazu",
          "river_stat": "1",
          "stage_datum": 0.209
        },
        {
          "reach": " Desembocadura",
          "river": "Guazu",
          "river_stat": "8000",
          "stage_datum": 0.327
        },
        {
          "reach": "4",
          "river": "Guazu",
          "river_stat": "4",
          "stage_datum": 0.717
        }
      ],
      "geometry": "DeltaParana_2016.g23",
      "geometry_id": 3,
      "id": 82,
      "plan_name": "hidrodelta_op-20240327_10hs",
      "start_datetime": "2024-04-26 13:17:08.026502",
      "status": "PENDING",
      "user_id": 1
    }

Response (code 400):

    {
      "error": "'NoneType' object has no attribute 'split'"
    }

@manulon
@azulzaietz
@federicoburman

**Comment by federicoburman** [comment]
Buenas Juan, tenemos que mejorar el mensaje de error alli. Pero lo que esta ocurriendo es que le estas pasando incorrectamente los archivos. Para hacerlo hay 2 maneras:
O pasarle el output del get con el full_content en true. (esto esta desde ayer a la noche). Que te devuelve los archivos en base 64. 
O hacer pasarle "project_file": "execution-plan/1/1.prj" De esa manera lo que hace es copiar ese archivo hacia la carpeta de la nueva.

**Comment by federicoburman** [comment]
Perdon, esta mergeado desde recien a dev lo de b64 para los execution files

**Comment by federicoburman** [comment]
Fijate tambien que en el ultimo merge le cambie el nombre del array `execution_files` a `files` par que sea igual a scheduled task

**Comment by cerobpm** [comment]
Ahora se creó la execution_task pero se copió sólo el archivo de la geometría

**Comment by federicoburman** [comment]
me podrias compartir el body que le estas pasando?

**Comment by cerobpm** [comment]
{
      "created_at": "2024-05-02 11:57:16.589656",
      "end_datetime": "2024-05-02 11:57:16.589653",
      "execution_output_list": [
        {
          "reach": " 2b",
          "river": "Parana",
          "river_stat": "223194.8",
          "stage_datum": 3.625
        },
        {
          "reach": " Desembocadura",
          "river": "SanAntonio",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "CanaldelEste",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "Mini",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "LaBarquita",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "BarcaGrande",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "Sauce",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "Bravo",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " Desembocadura",
          "river": "Gutierrez",
          "river_stat": "1960.748",
          "stage_datum": 0
        },
        {
          "reach": "1",
          "river": "CarabelasGrande",
          "river_stat": "33.3",
          "stage_datum": 0
        },
        {
          "reach": " Victoria",
          "river": "Victoria",
          "river_stat": "82.92",
          "stage_datum": 1.536
        },
        {
          "reach": " RioBaradero",
          "river": "RioBaradero",
          "river_stat": " 29.092*",
          "stage_datum": 0.641
        },
        {
          "reach": "4",
          "river": "Parana",
          "river_stat": "498.7283",
          "stage_datum": 1.37
        },
        {
          "reach": "3",
          "river": "Parana",
          "river_stat": "44071.76",
          "stage_datum": 0.714
        },
        {
          "reach": "3",
          "river": "Parana",
          "river_stat": "94846.95",
          "stage_datum": 1.642
        },
        {
          "reach": "3",
          "river": "Parana",
          "river_stat": "126030.6",
          "stage_datum": 1.954
        },
        {
          "reach": " 2b",
          "river": "Parana",
          "river_stat": "143588.9",
          "stage_datum": 1.981
        },
        {
          "reach": " 2b",
          "river": "Parana",
          "river_stat": "188533.7",
          "stage_datum": 3.032
        },
        {
          "reach": " Desembocadura",
          "river": "Lujan",
          "river_stat": "0",
          "stage_datum": 0
        },
        {
          "reach": " 2b",
          "river": "Parana",
          "river_stat": "237194.8",
          "stage_datum": 0
        },
        {
          "reach": " ParanaAA",
          "river": "Parana",
          "river_stat": "18.96",
          "stage_datum": 6.763
        },
        {
          "reach": " ParanaAA",
          "river": "Parana",
          "river_stat": "224000",
          "stage_datum": 9.432
        },
        {
          "reach": " Desembocadura",
          "river": "Palmas",
          "river_stat": "6246.783",
          "stage_datum": -0.337
        },
        {
          "reach": "8",
          "river": "Palmas",
          "river_stat": "21307.62",
          "stage_datum": 0
        },
        {
          "reach": "5",
          "river": "Palmas",
          "river_stat": "45033.09",
          "stage_datum": -0.656
        },
        {
          "reach": "4",
          "river": "Palmas",
          "river_stat": "49019.05",
          "stage_datum": 0.03
        },
        {
          "reach": "4",
          "river": "Palmas",
          "river_stat": "57113.41",
          "stage_datum": 0.418
        },
        {
          "reach": "3",
          "river": "Palmas",
          "river_stat": "68418.45",
          "stage_datum": 0.243
        },
        {
          "reach": "3",
          "river": "Palmas",
          "river_stat": "94654.47",
          "stage_datum": -0.556
        },
        {
          "reach": "2",
          "river": "Palmas",
          "river_stat": "101864.4",
          "stage_datum": 1.156
        },
        {
          "reach": " Desembocadura",
          "river": "Mini",
          "river_stat": "11.9",
          "stage_datum": -0.286
        },
        {
          "reach": "2",
          "river": "Lujan",
          "river_stat": "5.828",
          "stage_datum": -0.099
        },
        {
          "reach": "1",
          "river": "Lujan",
          "river_stat": "18.0191",
          "stage_datum": -0.074
        },
        {
          "reach": "1",
          "river": "Lujan",
          "river_stat": "24.421",
          "stage_datum": 0
        },
        {
          "reach": " Ibicuy",
          "river": "Ibicuy",
          "river_stat": "7.16",
          "stage_datum": 0.456
        },
        {
          "reach": " Desembocadura",
          "river": "Gutierrez",
          "river_stat": "19967.07",
          "stage_datum": 0.39
        },
        {
          "reach": "3",
          "river": "Guazu",
          "river_stat": "1",
          "stage_datum": 0.209
        },
        {
          "reach": " Desembocadura",
          "river": "Guazu",
          "river_stat": "8000",
          "stage_datum": 0.327
        },
        {
          "reach": "4",
          "river": "Guazu",
          "river_stat": "4",
          "stage_datum": 0.717
        }
      ],
      "files": [
        {
          "name": "execution-plan/93/DeltaParana_2016.g23"
        },
        {
          "name": "execution-plan/93/restart_file.rst"
        },
        {
          "name": "execution-plan/93/scheduled-task.p01"
        },
        {
          "name": "execution-plan/93/scheduled-task.prj"
        },
        {
          "name": "execution-plan/93/scheduled_task.u01"
        }
      ],
      "geometry": "DeltaParana_2016.g23",
      "geometry_id": 3,
      "id": 93,
      "plan_name": "hidrodelta_op-20240327_10hs",
      "result_files": [],
      "start_datetime": "2024-05-02 11:57:16.589648",
      "status": "PENDING",
      "user_id": 1
    }

**Comment by federicoburman** [comment]
@jbianchi81 @cerobpm 
Buenas Juan aca hay una decision de funcionalidad que hay que tomar.
Actualmente la api soporta 2 maneras de subir los archivos de una Execution plan.
1. Para cada archivo de configuracion,  le especificas el path de uno ya existente en minio en el body de la request. Por ejemplo`"project_file": "execution-plan/93/scheduled-task.prj` . Lo que hace despues el back es copiar ese archivo a la carpeta del execution plan recien creado.
2. En el body de la request le pasas el array files con **name y** **content**

Entonces las decisiones que hay que tomar aca son las siguientes:
Queres que soportemos que si no le pasas el content se intenten copiar los archivos? 
Seguimos soportando lo siguiente: `"project_file": "execution-plan/93/scheduled-task.prj`?
y por ultimo, si falla en subir un archivo. dejamos el execution plan creado o lo eliminamos?

**Comment by cerobpm** [comment]
> Queres que soportemos que si no le pasas el content se intenten copiar los archivos?
> Seguimos soportando lo siguiente: "project_file": "execution-plan/93/scheduled-task.prj?

Me parece que la segunda opción sería la más prolija porque indica qué es cada archivo. En ese caso habría que agregar "plan_file" y "restart_file" a la salida de GET /scheduled_task

> y por ultimo, si falla en subir un archivo. dejamos el execution plan creado o lo eliminamos?

Se puede notificar al usuario de los archivos faltantes y no eliminar el plan creado.

**Comment by federicoburman** [comment]
Hay un tema sobre eso que es que no guardamos que tipo de archivo es cada uno. Podriamos hacer un chequeo segun el tipo de archivo pero nos expondria a tener varios errores por no cazar algun tipo de archivo. Es decir, nosotros cuando guardamos un archivo de plan no nos guardamos en ningun lado que este sea el archivo de plan. A menos que tengas una manera de asegurarnos que tipo de terminacion tiene cada tipo de archivo no podriamos hacerlo

**Comment by cerobpm** [comment]
No se podría hacer que la salida de GET scheduled_task tenga:

      "files": [
        {
          "name": "scheduled-task/10/plan_template.txt",
          "type": "plan_file"
        },
        {
          "name": "scheduled-task/10/prj_template.txt",
          "type": "project_file"
        },
        {
          "name": "scheduled-task/10/restart_file.rst",
          "type": "restart_file"
        }
      ],

Así cuando se hace el POST se puede reconocer qué es cada archivo

**Comment by manulon** [comment]
Solucionado!
