### ISSUE TITLE
Formulario editor de corridas programadas: al agregar una fila a series de salida, la columna cero de escala no acepta decimales

### ISSUE THREAD

**Issue by cerobpm** [jbianchi81/gesina#26]
http://localhost:5001/view/schedule_tasks/10

En la pestaña Configuración de plan, en una fila nueva de series de salida, al ingresar un número decimal en el campo "cero de escala" e intentar Guardar tira el mensaje "Please select a valid value, The two nearest values are 0 and 1"

@manulon
@azulzaietz
@federicoburman

**Comment by federicoburman** [comment]
Lo miro

**Comment by federicoburman** [comment]
Listo! @jbianchi81 @cerobpm
