### ISSUE TITLE
Opción de importar/exportar configuraciones de simulaciones hidrodinámicas y corridas programadas

### ISSUE THREAD

**Issue by jbianchi81** [jbianchi81/gesina#8]
Deberá generarse un esquema (utilizando p. ej. jsonschema) contra el cual validar los archivos de configuración. Sería una alternativa a la carga mediante formulario, útil a la hora de duplicar configuraciones o migrar el sistema.

**Comment by azulzaietz** [comment]
Poder cargar los datos usando un csv o un JSON en lugar de llenar los formularios de la interfaz para hacer las simulaciones.
