### ISSUE TITLE
Generar una API con funciones de monitoreo y control

### ISSUE THREAD

**Issue by jbianchi81** [jbianchi81/gesina#9]
La API deberá replicar las funciones de la GUI, pero para interacción máquina-máquina. Deberá permitir, por ejempĺo:
- importar, exportar, actualizar y eliminar configuraciones de simulaciones hidrodinámicas
- importar, exportar, actualizar  y eliminar configuraciones de corridas programadas
- importar, exportar, actualizar  y eliminar geometrías
- importar, exportar, actualizar  y eliminar usuarios
- descargar listado de simulaciones hidrodinámicas, con filtrado opcional p. ej. por nombre, usuario, fecha de creación y estado.
- descargar listado de corridas programadas con filtrado opcional p. ej. por nombre, usuario y fecha de creación.
- descargar listado de geometrías, con fitrado opcional p. ej, por archivo, descripción, usuario y fecha de creación
- descargar listado de usuarios 
- ejecutar una corrida programada
- descargar los resultados de una corrida programada
- descargar los indicadores de actividad (cantidad de ejecuciones por día, tiempo promedio de ejecución por día) 

La API debe consumir/producir archivos en formato JSON (u otro formato de uso generalizado) que se puedan validar contra esquemas (generados p.ej usando jsonschema). Los esquemas deben estar publicados (por ejemplo en el repositorio de github).
Se deben requerir credenciales para autenticar a los usuarios (p.ej mediante token) 

La estructura de la API debe documentarse utilizando apidocs u otro estándar de uso generalizado y el documento debe estar disponible para su descarga. Opcionalmente puede disponibilizarse una página web de prueba de la API utlizando por ejemplo swagger-ui

Preferentemente, la API debe seguir los principios de diseño restful.

**Comment by azulzaietz** [comment]
Mismas funcionalidades que las actuales pero directamente desde API REST

**Comment by cerobpm** [comment]
Como para priorizar, comenzaría con las siguientes funcionalidades:
-  importar, exportar, actualizar y eliminar configuraciones de simulaciones hidrodinámicas
-  importar, exportar, actualizar y eliminar configuraciones de corridas programadas
-  descargar listado de simulaciones hidrodinámicas, con filtrado opcional p. ej. por nombre, usuario, fecha de creación y estado.
-  descargar listado de corridas programadas con filtrado opcional p. ej. por nombre, usuario y fecha de creación.

**Comment by federicoburman** [comment]
Consulta sobre el requerimiento de subir una configuracion de simulacion:
Cuando se quiere especificar cuales son los archivos quiere poder especificarle el nombre del archivo y que el servidor por dentro lo busque dentro de su repositorio de archivos? Es decir, el restart file tiene que ya estar subido previamente?
O quieren poder subirlo en la misma api request(esto seria un tanto mas complicado porque haria que el body de la request tenga el contenido de los archivos de ejecucion). 

@jbianchi81

**Comment by jbianchi81** [comment]
En el primer caso tendría que agregarse un endpoint para subir los archivos al repositorio. Y para que no se pisen los archivos de distintas configuraciones deberían ir a parar a carpetas separadas dentro del repositorio. Si es así me parece bien.

**Comment by azulzaietz** [comment]
Hola Juan! Cómo estás? 
Te mandamos un Mail hace unos días pero me parece que no lo viste. 
Nos gustaría tener una reunión con vos para que nos des feedback sobre lo que implementamos para este issue. 
Podrías esta semana? Decinos cuándo te quedaría mejor! 
Gracias! 
@federicoburman @manulon @jbianchi81 @cerobpm

**Comment by jbianchi81** [comment]
Hola Azul, 
Sí lo ví y respondí pero parece que no les llegó. Puedo hoy, mañana o el viernes

**Comment by azulzaietz** [comment]
Hola! Buenísimo
Mañana 18.30 te queda bien?

**Comment by jbianchi81** [comment]
Dale, quedamos así

**Comment by manulon** [comment]
@jbianchi81 https://meet.google.com/dhu-gkzn-xbs estamos en este link

**Comment by cerobpm** [comment]
Da error el endpoint para crear un execution_plan:

curl -X POST "http://localhost:5001/api/execution_plan" -H  "accept: */*" -H  "Authorization: Basic YWRtaW5AaW5hLmNvbS5hcjpwYXNzd29yZA==" -H  "Content-Type: application/json" -d "{\"created_at\":\"2024-03-08 12:48:54.715645\",\"end_datetime\":\"2024-03-08 12:48:54.715643\",\"execution_files\":[{\"name\":\"Modelo1-Atucha.g01\"}],\"execution_output_list\":[],\"geometry\":\"Modelo1-Atucha.g01\",\"geometry_id\":1,\"id\":2,\"plan_name\":\"ejemplo-inaaa\",\"result_files\":[],\"start_datetime\":\"2024-03-08 12:48:54.715638\",\"status\":\"PENDING\",\"user_id\":1}"

Response:
Code: 400 
Error: BAD REQUEST
{
  "error": "'NoneType' object has no attribute 'split'"
}

De todas maneras creó el execution_plan, pero con id=3

**Comment by federicoburman** [comment]
El error es que no le estas pasando execution files. Si te parece bien que se pueda crear un execution plan sin files entonce lo modificamos.

**Comment by cerobpm** [comment]
Entonces el mensaje de error debería informar eso. Lo mismo para cualquier error en el input

**Comment by cerobpm** [comment]
Con execution_files me da el mismo error:

curl -X POST "http://localhost:5001/api/execution_plan" -H  "accept: */*" -H  "Authorization: Basic YWRtaW5AaW5hLmNvbS5hcjpwYXNzd29yZA==" -H  "Content-Type: application/json" -d "{\"created_at\":\"2024-03-08 13:13:32.590060\",\"end_datetime\":\"2024-03-08 13:13:32.590058\",\"execution_files\":[{\"name\":\"DeltaParana_2016.p21\"},{\"name\":\"DeltaParana_2016.prj\"},{\"name\":\"DeltaParana_2016.u10\"},{\"name\":\"DeltaParana_2017.g01\"},{\"name\":\"Modelo1-Atucha.g01\"},{\"name\":\"restart_file.rst\"}],\"execution_output_list\":[],\"geometry\":\"Modelo1-Atucha.g01\",\"geometry_id\":1,\"id\":5,\"plan_name\":\"ejemplo-ina\",\"result_files\":[],\"start_datetime\":\"2024-03-08 13:13:32.590054\",\"status\":\"PENDING\",\"user_id\":1}"

{
  "error": "'NoneType' object has no attribute 'split'"
}

Igual la simulación la crea OK

**Comment by federicoburman** [comment]
Esto es algo que no documentamos correctamente. Los archivos que le pasas tienen que estar subidos previamente con el endpoint /execution_plan/upload_file o subidos por vos a las carpeta de minio_data/gesina. Y cuando le pasas el nombre le tenes que pasar el path de minio, por ejemplo si esta en minio_data/gesina/execution-plan le tenes que pasar {"name": "gesina/execution-plan/restart_file.rst"}.
Nos agrego la tarea de documentar esto tambien

**Comment by cerobpm** [comment]
Sería útil agregar un endpoint GET execution_plan/files que devuelva un listado de los archivos subidos.
Aparte tengo una duda: al subir un archivo con execution_plan/upload_file, éste está disponible para todos los execution_plans? Se sobreescribe un archivo preexistente con el mismo nombre?

**Comment by federicoburman** [comment]
ESta bueno ese endpoint, lo agregamos.
Si, cuando subis un archivo con ese endpoint se sube a la carpeta execution-plan y se sobreescribe si hay uno con el mismo nombre. Que comportamiento te gustaria que tenga? lo podemos modificar

**Comment by cerobpm** [comment]
Me parece que salvo para las geometrías (que pueden ser compartidas), los archivos deberían subirse a una carpetas propias de cada execution_plan, por ejemplo execution-plan/1, execution-plan/2, para evitar que se sobreescriban. O sea que habría que agregar el parámetro execution_plan_id al endpoint /upload_file, por ejemplo /execution_plan/{id}/upload_file
